### ISSUE TITLE
SauceRest : Getting SecurityUtils cannot be resolved at compilation

### ISSUE THREAD

**Issue by akumar2207** [saucelabs/saucerest-java#355]
Hi  Team ,
I'm using below maven dependency :-
              <dependency>
			<groupId>com.saucelabs</groupId>
			<artifactId>saucerest</artifactId>
			<version>2.0.4</version>
		</dependency>
and  with this version getting  **SecurityUtils cannot be resolved** at compilation .

**Import** 
import com.saucelabs.saucerest.SecurityUtils;

**Code** 
		try {
			String key = SAUCE_USERNAME + ":" + SAUCE_ACCESS_KEY;
			String auth_token = SecurityUtils.hmacEncode("HmacMD5", jobId, key); -> Getting compilation error
			return "https://saucelabs.com/jobs/" + jobId + "?auth=" + auth_token;
		} catch (IllegalArgumentException ex) {
		return "";
		}

## Environment

* Java JDK version that exhibits the issue:
* saucerest-java version that exhibits the issue:
* Operating System / version that exhibits the issue:
* Last configuration (Java, saucerest-java, OS, OS version) that did not exhibit the issue (if applicable):

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to logs

If your log files are really long consider creating a [GIST](https://gist.github.com) which is a paste of your _full_  logs, and link them here. Otherwise this report will be long and hard to read.

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

**Comment by sceiler** [comment]
Thanks but please confirm you are using the latest version of saucerest-java and also see the open questions under Environment.

**Comment by akumar2207** [comment]
Yes , I have tried with version 2.0.4 & 2.0.5 but its not working .
This line of code was working with 1.1.x maven versions.

**Comment by sceiler** [comment]
Java JDK version that exhibits the issue:
saucerest-java version that exhibits the issue:
Operating System / version that exhibits the issue:
Last configuration (Java, saucerest-java, OS, OS version) that did not exhibit the issue (if applicable):

**Comment by akumar2207** [comment]
JDK : jdk1.8.0_261
Windows operating system.

With above configuration it was working with 1.1.x version

**Comment by sceiler** [comment]
What windows version are you using?

**Comment by akumar2207** [comment]
Windows 10

**Comment by sceiler** [comment]
The latest CI build compiled and ran successfully. https://github.com/saucelabs/saucerest-java/actions/runs/4598818896

Although they were compiled with JDK 17. You could try and use a newer JDK version. Java 8 is 9 years old already. Please try using the latest LTS which is Java 17 or the latest version which would be Java 20

**Comment by akumar2207** [comment]
I just tried with 17 and 18 both .. Still same compilation error.
![image](https://user-images.githubusercontent.com/46046732/229581742-b799c0cd-0878-4d7b-ad26-644d1905ad7d.png)

**Comment by sceiler** [comment]
I need to check that. Btw setting the compliance level is not the same as using Java 18 for the project. 

You need to go to Project > Preferences > Java Build Path > Libraries and change it there.

**Comment by sceiler** [comment]
SecurityUtils got removed a lot of releases ago. Just remove the import from your project and you should be fine. No idea why Eclipse didn't help or do that for you after upgrading to a newer version of saucerest.
